### ISSUE TITLE
Custom layout for preference headers

### ISSUE THREAD

**Issue by chongbo2013** [michael-rapp/AndroidPreferenceActivity#11]
preference headers, i want to  add some SwitchPreference  .
my list has     headers and  SwitchPreference  and so on.

**Comment by chongbo2013** [comment]
i don't my settings  show all  head.

**Comment by michael-rapp** [comment]
Can you please explain your issue in a more detailed way? I don't understand your question.

**Comment by chongbo2013** [comment]
sorry . i will explain issue in a more detailed

**Comment by chongbo2013** [comment]
preference headers   ，how can i add a SwitchPreference  in the headers .

**Comment by chongbo2013** [comment]
i need some Options  headers like SwitchPreference.    can add to   preferenceheaders.xml

**Comment by michael-rapp** [comment]
There is no possibility to add a SwitchPreference to the preference headers in a XML resource. Please note, that preference headers are regular views instead of preferences.

However, in the documentation (which you can find in the `doc` folder as HTML files) there is a section called "3.3 Taking influence on the PreferenceHeaderAdapter". It is about how the appearance of preference headers can be changed. First, define the preference header, which should contain the switch, within your XML file similar to the other ones by specifying a title and optionally summary. Then you can reference the adapter, which is used to visualize the preference headers, by calling the method `getListAdapter():PreferenceHeaderAdapter` within your `PreferenceActivity`. The adapter provides the method `setViewId(int):void`, which allows to specify a custom layout file for visualizing preference headers. You can create a custom layout similar to the one given in `/res/layout/preference_header_item.xml` (it should provide the same views with identical ids), which contains an additional switch widget. Unfortunately, this will cause the layouts of all preference headers to be changed. So you have to create an implementation of the interface `PreferenceHeaderDecorator` and add it to the adapter by using the method `addDecorator(PreferenceHeaderDecorator):void`. The decorator's `onApplyDecorator`-method is called each time a preference header is about to be shown. Use it to hide the switch in all preferences instead of the relevant one.

**Comment by chongbo2013** [comment]
thank u very much
