### ISSUE TITLE
 little bug in Orientation change

### ISSUE THREAD

**Issue by mortezasun** [michael-rapp/AndroidPreferenceActivity#23]
I'm sorry, little bug in Orientation change , not keep state,
first launch: in android 6 api 23

![image 6](https://cloud.githubusercontent.com/assets/8259341/25553246/aa712072-2cc3-11e7-87dc-e6dc41f6a3f9.png)

and then rotate
![image 5](https://cloud.githubusercontent.com/assets/8259341/25553250/b5ad2152-2cc3-11e7-97b8-b7b7fd3e15b8.png)

**Comment by michael-rapp** [comment]
I will investigate on this, but it will take a few days.

**Comment by michael-rapp** [comment]
Sorry, I cannot reproduce this bug. How do you enable the RTL layout? I used the "Force RTL layout orientation"-option in the developer options of the Android settings and everything works well. It is awkward, that on your second screenshot the RTL layout is not used at all. This may indicate, that the RTL layout is not enabled correctly. Otherwise, it should at least cause the toolbar title ("SettingsTest") to be right-aligned, because this is handled by the Android support library.

**Comment by mortezasun** [comment]
Hi ,
I use this code for change language android and  then  use it , direction of layout changed  to right automatically
`   Configuration conf = new Configuration();
            String languageToLoad = "fa"; // your language
            Locale locale = new Locale(languageToLoad);
            Locale.setDefault(locale);
            conf.locale = locale;
           getApplicationContext().getResources().updateConfiguration(conf,getResources().getDisplayMetrics());
      `
after set this , that bug revealed

**Comment by michael-rapp** [comment]
I guess you are calling this code at the wrong place of the activity's lifecycle. Where do you call it? In the `onCreate`-method? Maybe you should set a debugging point to ensure, that the code is executed again after an orientation change.

**Comment by mortezasun** [comment]
No ,  I put this code in the application class , 
```
`public class MyApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

       Configuration conf = new Configuration();
        String languageToLoad = "fa"; // your language
        Locale locale = new Locale(languageToLoad);
        Locale.setDefault(locale);
        conf.locale = locale;
        getResources().updateConfiguration(conf, getResources().getDisplayMetrics());
    }
}`
```

**Comment by michael-rapp** [comment]
Alright, I was able to reproduce it. The problem with your code is, that the application classes' `onCreate`-method is only called for once when the app is started. After an orientation change, the method is not called again and the configuration is reset to the default. In order to overcome this issue you can implement the application class as follows:

```java
public class MyApp extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        setLocale();
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        setLocale();
    }

    private void setLocale() {
        Configuration conf = new Configuration();
        String languageToLoad = "fa"; // your language
        Locale locale = new Locale(languageToLoad);
        Locale.setDefault(locale);
        conf.locale = locale;
        getResources().updateConfiguration(conf, getResources().getDisplayMetrics());
    }

}
```

**Comment by mortezasun** [comment]
thanks  a lot michael-rapp , that's worked

**Comment by michael-rapp** [comment]
Glad to help...
