### ISSUE TITLE
Is there any way to listen to preference changes?

### ISSUE THREAD

**Issue by zubairehman** [michael-rapp/AndroidPreferenceActivity#27]
Hi,

first of all thanks for such a great library, i have been using it to populate preferences dynamically but in my case i have to read the preference value as well. Could you please specify how can i do that?

**Comment by michael-rapp** [comment]
Hi,

first of all I want to say that this library is only responsible for arranging and displaying preferences. It does not affect the way preferences work in general. Because of this, obtaining the values of preferences is always the same, regardless of whether you are using this library or not.

You should look into the following things:

* By registering an [`OnPreferenceChangeListener`](https://developer.android.com/reference/android/support/v7/preference/Preference.OnPreferenceChangeListener), you can observe when the value of a preference has changed.
* Most preferences provide a `getValue`-method or similar to retrieve the current value.
* By default, the value of a preference is stored automatically. Make sure that the preference has a key assigned to it, otherwise automatically storing its value will not work.

**Comment by zubairehman** [comment]
thanks for your response @michael-rapp. let me try and then i will get back to you on this :)

**Comment by zubairehman** [comment]
it worked, thanks :)

**Comment by michael-rapp** [comment]
Glad to hear that!
