### ISSUE TITLE
UI issue while adding new preference 

### ISSUE THREAD

**Issue by zubairehman** [michael-rapp/AndroidPreferenceActivity#28]
Hi,

I am getting white space before preference on some devices, please have a look at the attached screenshot.

Device: BlackView
OS: 6.0

![screenshot_20180827-110740](https://user-images.githubusercontent.com/7915601/44643444-04a28000-a9ea-11e8-86be-969cd0a7c753.png)

**Comment by michael-rapp** [comment]
I am not able to reproduce this issue using an emulator with Android 6.0.

Could you please post a screenshot with layout bounds enabled (go to the Android Settings app -> Developer options -> Show layout bounds). If the developer settings are not visible on your device, [here](https://www.greenbot.com/article/2457986/android/how-to-enable-developer-options-on-your-android-phone-or-tablet.html) is a manual how it can be enabled.

Also you could try to download the library's example app from [here](https://github.com/michael-rapp/AndroidPreferenceActivity/releases/download/6.0.2/AndroidPreferenceActivity-v6.0.2.apk) and run install it on your device. If the issue does not occur with the example app there must be a problem with your implementation.

**Comment by zubairehman** [comment]
here you go:
![screenshot_20180828-145451](https://user-images.githubusercontent.com/7915601/44715888-5a525780-aad2-11e8-8535-d70d3f23344a.png)

**Comment by michael-rapp** [comment]
Honestly, I don't have any idea where that space comes from. Could you please test if the issue is also there with the library's example app.

This is what it looks like for me:

![screenshot from 2018-08-29 22-27-23](https://user-images.githubusercontent.com/6638695/44813761-e8b20080-abda-11e8-936c-6650cf835adc.png)

**Comment by zubairehman** [comment]
sure, let me give it a try and get back to you :)

**Comment by michael-rapp** [comment]
@zubairehman Have you made any progress on this issue?

**Comment by zubairehman** [comment]
@michael-rapp i am still facing the same issue on few devices one of which is blackview.

**Comment by Kahtaf** [comment]
@michael-rapp I'm having this issue as well. Let me know if you need more information to help you debug. 

```
    implementation 'com.github.michael-rapp:android-material-preferences:5.1.2'
    implementation 'com.github.michael-rapp:android-preference-activity:7.0.1'
```
I didn't have this problem in this version. 
```
    implementation 'com.github.michael-rapp:android-material-preferences:4.0.2'
    implementation 'com.github.michael-rapp:android-preference-activity:6.0.3'
```

**Comment by michael-rapp** [comment]
Adding some additional white space to the left of the preferences seems to be Android's default behavior since a while. At least when using Android X's Material Design Components. This library uses it since version 7.0.0.

There is not much I can do about this as this library does not implement any preferences by itself. However, I could overwrite this behavior for the preferences that are provided by the library ["AndroidMaterialPreferences"](https://github.com/michael-rapp/AndroidMaterialPreferences).

Alternatively you could use a custom layout for your preferences (see [here](https://github.com/michael-rapp/AndroidMaterialPreferences)). [This](https://github.com/michael-rapp/AndroidPreferenceActivity/blob/master/library/src/main/res/layout/preference_layout.xml) layout is used by this library. You could use it as a reference and remove the ImageView for displaying the icon if not needed.
